---
algos:
#  - ArrayList
#  - BFSGraphList
#  - BFSGraphMatrix
#  - BinarySearch
#  - BTBFS
#  - BTInOrder
#  - BTPreOrder
#  - BTPostOrder
#  - BubbleSort
#  - CompareBinaryTrees
#  - DFSonBST
#  - DijkstraList
#  - LinearSearch
#  - LRU
#  - Map
#  - MazeSolver
#  - MinHeap
#  - Queue
#  - QuickSort
#  - SinglyLinkedList
#  - Stack
#  - Trie
#  - TwoCrystalBalls